server:
  port: 8080

spring:
  application:
    name: APP-IN-DEVELOPMENT
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true